site_name: 自动化测试
site_description: 自动化测试文档中心

pages:
- 主页: index.md
- QuickStart:
  - "项目结构和配置": 'webui_automation/project_structure.md'
  - "WEB页面自动化-SELENIUM管理页面元素": 'tips/selenium_in_a_wild_way.md'
  - "WEB页面自动化-开始": 'webui_automation/webui_automation_quickstart.md'
  - "WEB页面自动化-真实用例": 'webui_automation/webui_automation_realexample.md'
  - "API 自动化测试": 'api_automation/APIAutomation.md'
  - "API 自动化测试常见问题": 'api_automation/api_testing_qa.md'
  - "工作流测试之指定审批节点": 'activity_automation/activity_automation_defined_employees.md'
  - "工作流测试之动态审批节点": 'activity_automation/activity_automation_dynamic.md'
- 自动化测试模块介绍:
  - "目的" : 'intro/automation-purpose.md'
  - "基本模块的作用" : 'intro/automation-framework-impl.md'
  - "页面自动化-页面元素的使用": 'webui_automation/self_defined_elements.md'
  - "页面自动化-页面元素方法查询": 'webui_automation/element_handler.md'
  - "页面自动化-页面代码生成": 'webui_automation/pageobject_codegenerator.md'
  - "页面自动化-WebTestActionBuilder": 'webui_automation/build_test.md'
- 接口自动化测试:
  -  "接口测试－WEB接口常见的实现方法": 'api_automation/web接口测试.md'
  -  "API 自动化测试": 'api_automation/APIAutomation.md'
  -  "API自动化测试-进阶": 'api_automation/API自动化测试-进阶.md'
- Tips:
  - "WebUI Debug": 'tips/WebTest_Debug.md'
  - "FindByRef annotation  使用": 'tips/find_by_ref.md'
  - "verification 注解使用": 'best_practice/verification_annotation.md'
  - "JAVA 自动化测试代码规范": 'best_practice/code_style.md'
  - "一个简单测试用例的自动化实例": 'best_practice/simple_ui_case.md'
  - "数据库操作": 'database/Database.md'
  - "TestNG 测试XML配置": 'tips/testng-xml-configuration.md'
  - "使用自己的用户名和密码获取万能密码": 'tips/use_own_password.md'
  - "JSON处理": 'tips/JsonHelper.md'
  - "Page Object/Page Factory": 'tips/page_object.md'
  - "TreeElement 使用": 'tips/TreeElement.md'
  - "添加了Expectation的WebDriver操作": 'tips/WebDriverHelper.md'
  - "WebDriver原生操作": 'tips/WebDriver操作.md'
  - "编写测试步骤的不同方法": 'tips/how_to_write_teststeps.md'
  - "重复填写控件使用": 'tips/repeatable_elements.md'
  - "StateElementReferneceException": 'tips/StateElementReferneceException.md'
  - "DateHelper": 'tips/DateHelper.md'
  - "数据库验证": 'tips/database_assetion.md'
  - "预设条件数据的更新和回滚": 'tips/database_update.md'
  - "TestNG测试常见问题": 'tips/testng_faq.md'
  - "TestNG 定制报表简单原理": 'tips/simplest_testngreport.md'
  - "Page Factory 模式原理": 'tips/PageFactory.md'
  - "随机数据": 'tips/random_data.md'
  - "动态测试数据构建": 'tips/data_construct_by_context.md'
- Git:
  - "Git 基础": "git/git_basic.md"

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: pink
    accent: pink
  logo: 'logo-white.svg'
  favicon: 'favicon.png'
# theme: Cosmo
